name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: tshirts build
      run: |
        g++ -Wall -Wextra -Werror tshirts.c -o tshirts.out
        
    - name : tshirts run
      run: ./tshirts.out
      
    - name: misaligned build
      run: |
        g++ -Wall -Wextra -Werror misaligned.c -o misaligned.out
        
    - name: misaligned run
      run: ./misaligned.out
      
    - name: alerter build
      run: |
        g++ -Wall -Wextra -Werror alerter.c -o alerter.out
    
    - name : alerter run
      run: ./alerter.out
